In [1]:
from pickle import load
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from nltk.cluster import KMeansClusterer, euclidean_distance,cosine_distance


In [2]:
with open("df after category.pcl", 'rb') as file:
    df: pd.DataFrame = load(file)

In [3]:
df.head()

IN  reference’,  realities?  karşı.  (March  skilfully  Oppositions  \
1   0            0           0       0       0          0            0   
2   0            0           0       0       0          0            0   
3   0            0           0       0       0          0            0   
4   0            0           0       0       0          0            0   
5   0            0           0       0       0          0            0   

   facilirarely  (technology  placemarks,  ...  dilemma:  difficulties,  \
1             0            0            0  ...         0              0   
2             0            0            0  ...         0              0   
3             0            0            0  ...         0              0   
4             0            0            0  ...         0              0   
5             0            0            0  ...         0              0   

   (green  838  112–124.  suffocating.  (Greece),  quad,  Seventy-five  ,069  
1       0    0         0             0          0      0             0     0  
2       0    0         0             0          0      0             0     0  
3       0    0         0             0          0      0             0     0  
4       0    0         0             0          0      0             0     0  
5       0    0         0             0          0      0             0     0  

[5 rows x 149856 columns]

In [4]:
X=df.drop(["category"],axis=1)
y=df["category"]

In [5]:
# X.head()

In [24]:
model=KMeansClusterer(4, euclidean_distance, repeats=2,avoid_empty_clusters=False)
# model=KMeansClusterer(4, cosine_distance, repeats=10,avoid_empty_clusters=True)

clusters = model.cluster(X.to_numpy(), True)

In [23]:
# print("Clustered:", X)
print("As:", clusters)
len(clusters)

As: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


198

In [20]:
# print("Means:", model.means())

In [21]:
for x in model.means():
    print(x)

[1. 0. 0. ... 0. 0. 1.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.17435897 0.00512821 0.00512821 ... 0.00512821 0.01538462 0.        ]


In [28]:
from math import log

In [37]:
log(4000,150000)

0.6959034937852153